import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../firebasecon/firebase'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { ToastProvider } from "@/components/providers/toaster-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <ClerkProvider>
      <body className={inter.className}>
        <ToastProvider />
        {children}
        
      </body>
      </ClerkProvider>
    </html>
    
  );
}
